import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm'],
  target: 'node20',
  platform: 'node',
  outDir: 'dist',
  clean: true,
  sourcemap: true,
  splitting: false,
  banner: {
    js: '#!/usr/bin/env node',
  },
  // Externalize all deps — use CJS-compatible imports in source
  external: [
    'react',
    'react/jsx-runtime',
    'ink',
    'ink-select-input',
    'ink-spinner',
    'ink-text-input',
    'node-forge',
    'commander',
    'chalk',
    'hono',
    '@hono/node-server',
    'chokidar',
    'jiti',
    'minimatch',
    // Node builtins
    'http',
    'https',
    'tls',
    'url',
    'fs',
    'path',
    'events',
    'stream',
    'child_process',
    'crypto',
    'net',
    'os',
    'util',
    'buffer',
    'node:http',
    'node:https',
    'node:tls',
    'node:url',
    'node:fs',
    'node:path',
    'node:events',
    'node:stream',
    'node:child_process',
    'node:crypto',
    'node:net',
    'node:os',
    'node:util',
    'node:buffer',
  ],
  esbuildOptions(options) {
    options.jsx = 'automatic';
  },
});
